spring.application.name=OnlineExamination

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/exam?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:Tsr@#123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=${JWT_SECRET:8f2b5a8c1e4d7f903a6c1b2d4e5f60718293ab4cd5ef60718293ab4cd5ef6071}
